{
    'env': { 'browser': true, 'es6': true, 'node': true },
    'extends':
        [
            'eslint:recommended',
            'prettier',
            'plugin:@typescript-eslint/recommended',
        ],
    'plugins': ['prettier', '@typescript-eslint'],
    'parser': '@typescript-eslint/parser',
    'parserOptions':
        {
            'ecmaVersion': 2020,
            'sourceType': 'module',
            'allowImportExportEverywhere': true,
            parser '@typescript-eslint/parser',
        },
    'rules':
        {
            'indent': 'off',
            '@typescript-eslint/indent': 'off',
            '@typescript-eslint/explicit-function-return-type': 'off',
            'prettier/prettier': 'error',
            'camelcase': ['error'],
            'eqeqeq': ['error', 'always'],
            '@typescript-eslint/no-var-requires': 0,
        },
}
